

run_name: test

target_dataset: MMWebQA

generation_model: Qwen2.5_VL_7B

retrieval_results_path: /root/LILaC/algorithm_results/LILaC/MMWebQA/retrieval/mmembed_default.jsonl

num_components: 9

force_overwrite: true

num_gpus : 4

images_subpath: image_components

path_to_model: /root/LILaC/Models/Qwen2-VL-7B-Instruct

text_only: false