
MultimodalQA: 
  component:  "${REPO_ROOT}/datasets/MultimodalQA/QAs_dev_labeled.json"
  page:       "${REPO_ROOT}/datasets/M3DocVQA/M3DocVQA_dev_labeled.json"
WebQA: 
  component:  null
  page:       null
MMCoQA:
  component:  "${REPO_ROOT}/datasets/MMCoQA/QAs_dev_labeled.json"
  page:       "${REPO_ROOT}/datasets/MMCoQA/QAs_dev_page_labeled.json"
MP-DocVQA:
  component:  null
  page:       "${REPO_ROOT}/datasets/MP-DocVQA/QAs_dev.json"
SlideVQA:
  component:  null
  page:       "${REPO_ROOT}/datasets/SlideVQA/QAs_dev.json"
InfoVQA:
  component:  null
  page:       "${REPO_ROOT}/datasets/InfoVQA/QAs_dev.json"